Repository DDD-Community/fridge-link-server, pull requests merged in 2024-02, with the labels that each got.

#17 Hotfix-16 : @PostMapping 중복 매핑 해결
  src/main/kotlin/mara/server/domain/friend/FriendshipController.kt
Labels: bug

#18 MARA-43 : AWS S3 이미지 업로드 기능 구현
  .github/workflows/deploy.yaml
  build.gradle.kts
  src/main/kotlin/mara/server/config/s3/S3Config.kt
  src/main/kotlin/mara/server/domain/s3/S3Controller.kt
  src/main/kotlin/mara/server/domain/s3/S3Service.kt
  src/main/resources/application-dev.yml
Labels: enhancement

#13 Mara 40 : 나눔 CRUD 구현
  src/main/kotlin/mara/server/domain/share/ApplyShare.kt
  src/main/kotlin/mara/server/domain/share/ApplyShareRepository.kt
  src/main/kotlin/mara/server/domain/share/Share.kt
  src/main/kotlin/mara/server/domain/share/ShareController.kt
  src/main/kotlin/mara/server/domain/share/ShareDto.kt
  src/main/kotlin/mara/server/domain/share/ShareRepository.kt
  src/main/kotlin/mara/server/domain/share/ShareService.kt
  src/main/kotlin/mara/server/domain/user/UserController.kt
Labels: enhancement

#21 MARA-42 : 식재료상세 이름(name) 추가 및 기능 적용
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetail.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailDto.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailService.kt
Labels: enhancement

#22 로그인 시 계정 정보 없으면 필요한 정보 리턴, 보드 제거
  src/main/kotlin/mara/server/auth/google/GoogleApiClient.kt
  src/main/kotlin/mara/server/auth/kakao/KakaoApiClient.kt
  src/main/kotlin/mara/server/domain/board/Board.kt
  src/main/kotlin/mara/server/domain/board/BoardController.kt
  src/main/kotlin/mara/server/domain/board/BoardDto.kt
  src/main/kotlin/mara/server/domain/board/BoardRepository.kt
  src/main/kotlin/mara/server/domain/board/BoardService.kt
  src/main/kotlin/mara/server/domain/share/ShareService.kt
  src/main/kotlin/mara/server/domain/user/AuthDto.kt
  src/main/kotlin/mara/server/domain/user/User.kt
  src/main/kotlin/mara/server/domain/user/UserController.kt
  src/main/kotlin/mara/server/domain/user/UserDto.kt
  src/main/kotlin/mara/server/domain/user/UserRepository.kt
  src/main/kotlin/mara/server/domain/user/UserService.kt
Labels: enhancement

#23 MARA-54 : 화면설계서 기반 식자재 추가 API 개발, 리팩토링
  src/main/kotlin/mara/server/domain/ingredient/IngredientController.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetail.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailController.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailDto.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailRepository.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailService.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDto.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientService.kt
  src/main/kotlin/mara/server/domain/refrigerator/Refrigerator.kt
  src/main/kotlin/mara/server/domain/refrigerator/RefrigeratorController.kt
  src/main/kotlin/mara/server/domain/refrigerator/RefrigeratorDto.kt
  src/main/kotlin/mara/server/domain/refrigerator/RefrigeratorService.kt
  src/main/kotlin/mara/server/domain/share/ShareService.kt
Labels: enhancement

#24 MARA-56 : Refresh Token을 위한 Redis 추가
  build.gradle.kts
  src/main/kotlin/mara/server/auth/jwt/JwtFilter.kt
  src/main/kotlin/mara/server/auth/jwt/JwtProvider.kt
  src/main/kotlin/mara/server/config/redis/RedisConfig.kt
  src/main/kotlin/mara/server/config/redis/RefreshToken.kt
  src/main/kotlin/mara/server/config/redis/RefreshTokenRepository.kt
  src/main/kotlin/mara/server/config/swagger/SwaggerConfig.kt
  src/main/kotlin/mara/server/domain/user/AuthDto.kt
  src/main/kotlin/mara/server/domain/user/UserDto.kt
  src/main/kotlin/mara/server/domain/user/UserService.kt
  src/main/resources/application-dev.yml
Labels: enhancement

#27 HOTFIX-26 : SecurityFilterChain H2 관련 url 변경
  .gitignore
  src/main/kotlin/mara/server/auth/security/SecurityConfig.kt
Labels: bug

#29 MARA 70 - baseEntity 생성, 적용
  src/main/kotlin/mara/server/common/BaseEntity.kt
  src/main/kotlin/mara/server/domain/friend/Friendship.kt
  src/main/kotlin/mara/server/domain/ingredient/Ingredient.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetail.kt
  src/main/kotlin/mara/server/domain/refrigerator/Refrigerator.kt
  src/main/kotlin/mara/server/domain/share/ApplyShare.kt
  src/main/kotlin/mara/server/domain/share/Share.kt
  src/main/kotlin/mara/server/domain/user/User.kt
Labels: enhancement

#32 refactor: googleEmail "" 로 들어갈 때 예외 처리
  src/main/kotlin/mara/server/domain/user/UserService.kt
Labels: bug

#35 HOTFIX-33 : SSL 인증서 적용 설정 작업
  src/main/kotlin/mara/server/auth/security/SecurityConfig.kt
  src/main/kotlin/mara/server/config/swagger/SwaggerConfig.kt
  src/main/kotlin/mara/server/domain/HealthController.kt
Labels: enhancement

#28 MARA-67 : Figma 화면설계서 기반 기능 점검을 통한 리팩토링 작업 수행
  src/main/kotlin/mara/server/config/pageable/PageableConfig.kt
  src/main/kotlin/mara/server/config/querydsl/QueryDslConfig.kt
  src/main/kotlin/mara/server/domain/friend/FriendRefrigeratorController.kt
  src/main/kotlin/mara/server/domain/friend/FriendRefrigeratorDto.kt
  src/main/kotlin/mara/server/domain/friend/FriendRefrigeratorService.kt
  src/main/kotlin/mara/server/domain/friend/FriendshipController.kt
  src/main/kotlin/mara/server/domain/friend/FriendshipRepository.kt
  src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientController.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailController.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailDto.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailRepository.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailService.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientRepository.kt
  src/main/kotlin/mara/server/domain/refrigerator/Refrigerator.kt
  src/main/kotlin/mara/server/domain/refrigerator/RefrigeratorController.kt
  src/main/kotlin/mara/server/domain/refrigerator/RefrigeratorRepository.kt
  src/main/kotlin/mara/server/domain/refrigerator/RefrigeratorService.kt
  src/main/kotlin/mara/server/domain/s3/S3Controller.kt
  src/main/kotlin/mara/server/domain/s3/S3Service.kt
  src/main/kotlin/mara/server/domain/user/UserRepository.kt
Labels: refactoring

#37 MARA-69: 나눔 paging 처리, 등록순, 마감 순 정렬, 나눔 내역 조회 개발
  src/main/kotlin/mara/server/domain/share/ApplyShareRepository.kt
  src/main/kotlin/mara/server/domain/share/ShareController.kt
  src/main/kotlin/mara/server/domain/share/ShareDto.kt
  src/main/kotlin/mara/server/domain/share/ShareRepository.kt
  src/main/kotlin/mara/server/domain/share/ShareService.kt
  src/main/kotlin/mara/server/domain/user/UserController.kt
Labels: refactoring

#36 MARA-75 : 화면설계서 기반 API 점검 및 리팩토링 2차
  src/main/kotlin/mara/server/domain/HealthController.kt
  src/main/kotlin/mara/server/domain/friend/FriendRefrigeratorDto.kt
  src/main/kotlin/mara/server/domain/friend/FriendshipController.kt
  src/main/kotlin/mara/server/domain/friend/FriendshipRepository.kt
  src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailRepository.kt
  src/main/kotlin/mara/server/domain/share/ShareService.kt
  src/main/kotlin/mara/server/domain/user/User.kt
  src/main/kotlin/mara/server/domain/user/UserController.kt
  src/main/kotlin/mara/server/domain/user/UserDto.kt
  src/main/kotlin/mara/server/domain/user/UserRepository.kt
  src/main/kotlin/mara/server/domain/user/UserService.kt
Labels: refactoring

#38 MARA 77: 나눔 페이징 정렬 디폴트값적용, status 스트링으로 변경
  src/main/kotlin/mara/server/domain/share/Share.kt
  src/main/kotlin/mara/server/domain/share/ShareDto.kt
  src/main/kotlin/mara/server/domain/share/ShareRepository.kt
Labels: refactoring

#39 MARA-78 : FE API 연동 핫픽스 작업
  src/main/kotlin/mara/server/domain/friend/FriendshipRepository.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailRepository.kt
  src/main/kotlin/mara/server/domain/share/ShareRepository.kt
  src/main/kotlin/mara/server/domain/user/UserDto.kt
Labels: bug, enhancement

#43 HOTFIX-43: 본인 게시글 까지 조회 되게 변경
  src/main/kotlin/mara/server/domain/share/ShareRepository.kt
Labels: bug

#41 MARA-83 : FE API 연동 테스트 리팩토링 3차
  src/main/kotlin/mara/server/domain/friend/FriendRefrigeratorDto.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailController.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailDto.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailRepository.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailService.kt
Labels: bug, enhancement

#45 HOTFIX-44 : 나눔 상세 ,게시자 정보 추가, 신청한 사용자 이름,프로필 이미지 추가
  src/main/kotlin/mara/server/domain/share/ShareController.kt
  src/main/kotlin/mara/server/domain/share/ShareDto.kt
  src/main/kotlin/mara/server/domain/share/ShareService.kt
Labels: refactoring

#46 ISSUE-42 : 사용자 식자재 수, 나눔 수, 친구 수 조회 API 추가 개발
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailRepository.kt
  src/main/kotlin/mara/server/domain/ingredient/IngredientDetailService.kt
  src/main/kotlin/mara/server/domain/share/ApplyShareRepository.kt
  src/main/kotlin/mara/server/domain/share/ShareRepository.kt
  src/main/kotlin/mara/server/domain/user/UserController.kt
  src/main/kotlin/mara/server/domain/user/UserDto.kt
  src/main/kotlin/mara/server/domain/user/UserService.kt
Labels: enhancement

#48 MARA-87 : 최종 배포 전 코드 리팩토링
  src/main/kotlin/mara/server/domain/friend/FriendRefrigeratorService.kt
  src/main/kotlin/mara/server/domain/friend/FriendshipController.kt
  src/main/kotlin/mara/server/domain/friend/FriendshipDto.kt
  src/main/kotlin/mara/server/domain/friend/FriendshipRepository.kt
  src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
  src/main/kotlin/mara/server/domain/s3/S3Service.kt
  src/main/kotlin/mara/server/domain/user/UserRepository.kt
  src/main/resources/application-dev.yml
Labels: bug, enhancement
